# Generated by Django 4.0.4 on 2022-09-03 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sew', '0002_contact_delete_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=122)),
                ('lastname', models.CharField(max_length=122)),
                ('mail', models.CharField(max_length=122)),
                ('phone', models.CharField(max_length=122)),
                ('desc', models.TextField(max_length=122)),
            ],
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
