# Generated by Django 4.0.4 on 2022-09-04 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sew', '0003_reach_delete_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_Signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=122)),
                ('lastname', models.CharField(max_length=122)),
                ('mail', models.CharField(max_length=122)),
                ('phone', models.CharField(max_length=122)),
                ('password', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=122)),
            ],
        ),
    ]
